apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name:  amer-west-project-kubeconfig
  namespace: ucp-token-generator
spec:
  secretStoreRef:
    kind: SecretStore
    name: k8s-store
  target:
    name: amer-west-project-kubeconfig
    template:
      engineVersion: v2
      data:
        value.yaml: |
          apiVersion: v1
          clusters:
          - cluster:
              server: https://api.tanzu.cloud.vmware.com/org/77aee83b-308f-4c8e-b9c4-3f7a6f19ba75/project/3b65ba5e-52a4-4666-ad29-4eefab93127b
            name: sa-tanzu-platform:AMER-West
          contexts:
          - context:
              cluster: sa-tanzu-platform:AMER-West
              user: sa-tanzu-platform-user
            name: sa-tanzu-platform:AMER-West
          current-context: sa-tanzu-platform:AMER-West
          kind: Config
          preferences: {}
          users:
          - name: sa-tanzu-platform-user
            user:
              token: "{{ .token }}"
  data:
  - secretKey: token
    remoteRef:
      key: ucp-access-token
      property: access_token

