apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: amer-west-project
  namespace: tpk8s
spec:
  force: false
  interval: 1m0s
  path: ./deploy/tpk8s/AMER-West
  prune: true
  sourceRef:
    kind: GitRepository
    name: tpk8s