apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: test-ucp
  namespace: iris-blue
spec:
  path: ./clusters/aks.00439d3b.tmc-clusters.iris-test/namespaces
  prune: true
  serviceAccountName: tenant-flux-reconciler
  sourceRef:
    kind: GitRepository
    name: iris-blue
  targetNamespace: iris-blue
  kubeConfig:
    secretRef:
      Name: